apiVersion: v1
kind: Service
metadata:
  namespace: ad-api
  name: nginx-app3
  labels:
    app: nginx-app3
spec:
  selector:
    app: nginx-app3
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app3
  namespace: ad-api
  labels:
    app: nginx-app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app3
  template:
    metadata:
      labels:
        app: nginx-app3
    spec:
      containers:
      - name: nginx-app3
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        image: 740271638955.dkr.ecr.ap-northeast-2.amazonaws.com/nginx:1
        ports:
        - containerPort: 80
